# Generated by Django 5.2.9 on 2026-01-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyorder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
